<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://example.com/kafka/customer-notification"
           xmlns="http://example.com/kafka/customer-notification"
           elementFormDefault="qualified">

    <xs:simpleType name="uuidType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9a-fA-F\-]{36}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="customerNotification" type="CustomerNotification"/>

    <xs:complexType name="CustomerNotification">
        <xs:sequence>
            <xs:element name="id" type="uuidType"/>
            <xs:element name="customerId" type="uuidType"/>
            <xs:element name="createdAt" type="xs:dateTime"/>
            <xs:element name="channel" type="xs:string"/>
            <xs:element name="message" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
